Traceback (most recent call last):
  File "/Users/Reho0001/opt/anaconda3/envs/yambopy-test/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/Reho0001/opt/anaconda3/envs/yambopy-test/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Reho0001/opt/anaconda3/envs/yambopy-test/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Reho0001/opt/anaconda3/envs/yambopy-test/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/Reho0001/opt/anaconda3/envs/yambopy-test/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/Reho0001/opt/anaconda3/envs/yambopy-test/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/Reho0001/opt/anaconda3/envs/yambopy-test/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import yambopy
from yambopy import *

# Add to sys.path if not already present
if script_dir not in sys.path:
    sys.path.insert(0, script_dir)

# plotting library
import matplotlib.pyplot as plt
# Import objects for IO of LetzElPhC
from yambopy.letzelphc_interface.lelphcdb import LetzElphElectronPhononDB
# Import optical properties objects for post-processing
from yambopy.optical_properties.luminescence import Luminescence

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 5[0m
[1;32m      2[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01myambopy[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      4[0m [38;5;66;03m# Add to sys.path if not already present[39;00m
[0;32m----> 5[0m [38;5;28;01mif[39;00m [43mscript_dir[49m [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m sys[38;5;241m.[39mpath:
[1;32m      6[0m     sys[38;5;241m.[39mpath[38;5;241m.[39minsert([38;5;241m0[39m, script_dir)
[1;32m      8[0m [38;5;66;03m# plotting library[39;00m

[0;31mNameError[0m: name 'script_dir' is not defined

